// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MetaTest$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MetaTest";
  readonly sourceName: "contracts/MetaTest.sol";
  readonly abi: [{"inputs":[],"name":"getNum","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"num","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x608060405260025f553480156012575f5ffd5b50608980601e5f395ff3fe6080604052348015600e575f5ffd5b50600436106030575f3560e01c80634e70b1dc14603457806367e0badb14604d575b5f5ffd5b603b5f5481565b60405190815260200160405180910390f35b5f54603b56fea26469706673582212207c7b3b7d6f2e84730860a5ac103e45c50e6855fdd1824bdce5903fc9806aa96264736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106030575f3560e01c80634e70b1dc14603457806367e0badb14604d575b5f5ffd5b603b5f5481565b60405190815260200160405180910390f35b5f54603b56fea26469706673582212207c7b3b7d6f2e84730860a5ac103e45c50e6855fdd1824bdce5903fc9806aa96264736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/MetaTest.sol";
  readonly buildInfoId: "solc-0_8_28-248cd41834e72b77cd30eca24f9953efe7a0f5c2";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MetaTest"]: MetaTest$Type;
    ["contracts/MetaTest.sol:MetaTest"]: MetaTest$Type;
  }
}