/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MetaTest, MetaTestInterface } from "../../contracts/MetaTest.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getNum",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "num",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405260025f553480156012575f5ffd5b50608980601e5f395ff3fe6080604052348015600e575f5ffd5b50600436106030575f3560e01c80634e70b1dc14603457806367e0badb14604d575b5f5ffd5b603b5f5481565b60405190815260200160405180910390f35b5f54603b56fea26469706673582212207c7b3b7d6f2e84730860a5ac103e45c50e6855fdd1824bdce5903fc9806aa96264736f6c634300081c0033";

  
      type MetaTestConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MetaTestConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MetaTest__factory extends ContractFactory {
    
      constructor(...args: MetaTestConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MetaTest & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MetaTest__factory {
      return super.connect(runner) as MetaTest__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MetaTestInterface {
      return new Interface(_abi) as MetaTestInterface;
    }
    
    override attach(address: string | Addressable): MetaTest {
      return super.attach(address) as MetaTest;
    }
  static connect(address: string, runner?: ContractRunner | null): MetaTest {
      return new Contract(address, _abi, runner) as unknown as MetaTest;
    }
  }

  
  