/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MetaOracle, MetaOracleInterface } from "../../contracts/MetaOracle.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "initialPrice",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "getPrice",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "roundId",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "answer",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "startedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "updatedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "answeredInRound",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "newPrice",
        "type": "int256"
      }
    ],
    "name": "setPrice",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b50604051610134380380610134833981016040819052602b916031565b5f556047565b5f602082840312156040575f5ffd5b5051919050565b60e1806100535f395ff3fe6080604052348015600e575f5ffd5b5060043610603a575f3560e01c806398d5fdca14603e578063f7a30806146053578063feaf968c146064575b5f5ffd5b5f546040519081526020015b60405180910390f35b6062605e3660046095565b5f55565b005b5f546040805160018082526020820193909352429181018290526060810191909152608081019190915260a001604a565b5f6020828403121560a4575f5ffd5b503591905056fea26469706673582212204e0f7850a59d9b45e20935530b33bb32d6757a58ebd4d60fca2f6bd7a228fed364736f6c634300081c0033";

  
      type MetaOracleConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MetaOracleConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MetaOracle__factory extends ContractFactory {
    
      constructor(...args: MetaOracleConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(initialPrice, overrides || {});
    };
    override deploy(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(initialPrice, overrides || {}) as Promise<MetaOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MetaOracle__factory {
      return super.connect(runner) as MetaOracle__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MetaOracleInterface {
      return new Interface(_abi) as MetaOracleInterface;
    }
    
    override attach(address: string | Addressable): MetaOracle {
      return super.attach(address) as MetaOracle;
    }
  static connect(address: string, runner?: ContractRunner | null): MetaOracle {
      return new Contract(address, _abi, runner) as unknown as MetaOracle;
    }
  }

  
  